name: burst2safe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python<3.10
  - pip
  - gdal
  - shapely>=2
  - numpy<2.1.0
  - lxml
  - tifffile>=2022.04.22
  - asf_search
  - dateparser!=1.1.0
  - aiohttp
  # For packaging, and testing
  - pytest
  - pytest-cov
  - pytest-dependency
  - ruff
