name: Golden Test

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

jobs:
  pytest-golden-develop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python_version }}

      - name: Pytest in conda environment
        shell: bash -l {0}
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: |
          python -m pip install --no-deps .
          pytest -m golden -k 'not test_golden_compare' 

      - uses: actions/upload-artifact@v4
        with:
          name: develop.tar
          path: ./develop.tar
          if-no-files-found: error
          retention-days: 3
          compression-level: 0
          overwrite: true

  pytest-golden-main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python_version }}

      - name: Pytest in conda environment
        shell: bash -l {0}
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: |
          python -m pip install --no-deps .
          pytest -m golden -k 'not test_golden_compare' 

      - uses: actions/upload-artifact@v4
        with:
          name: main.tar
          path: ./main.tar
          if-no-files-found: error
          retention-days: 3
          compression-level: 0
          overwrite: true

  pytest-golden-compare:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: actions/download-artifact@v4
        with:
          name: develop.tar
          path: ./develop.tar

      - uses: actions/download-artifact@v4
        with:
          name: main.tar
          path: ./main.tar

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python_version }}

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps .
          pytest -m golden -k 'test_golden_compare' 
